### ISSUE TITLE
How install?

### ISSUE THREAD

**Issue by tsebis** [mktcode/polotrend#1]
How install it?

**Comment by mktcode** [comment]
Like described in the readme...

```
git clone git@github.com:mktcode/polotrend.git
cd polotrend
composer install
bower install
```
Do you have any specific problems?

**Comment by tsebis** [comment]
but only in the cmd? when i use composer and bower install appear "this command is unknown"

**Comment by mktcode** [comment]
You need to have composer and bower installed. See https://getcomposer.org/ and https://bower.io/
These are very very common tools.
